all: check_1 check_2 check_3 check_4 check_5 check_6 check_7

check_1: check_1.ml
	corebuild check_1.native

check_2: check_2.ml
	corebuild check_2.native

check_3: check_3.ml
	corebuild check_3.native

check_4: check_4.ml
	corebuild check_4.native

check_5: check_5.ml
	corebuild check_5.native

check_6: check_6.ml
	corebuild check_6.native

check_7: check_7.ml
	corebuild check_7.native

check_8: check_8.ml
	corebuild check_8.native

clean:
	rm -rf *.native _build
