all: check_7 check_8 check_9 check_10

check_7: check_7.ml
	corebuild check_7.native

check_8: check_8.ml
	corebuild check_8.native

check_9: check_9.ml
	corebuild check_9.native

check_10: check_10.ml
	corebuild check_10.native

clean:
	rm -rf *.native _build
